language: python
sudo: false
python:
- '3.6'
- '3.5'
- '2.7'
install:
- pip install pip -U
- pip install codecov tox
script:
- tox -e flake8 -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
after_success:
- codecov --flags $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
